version: '3.8'

services:
  ubuntu-duo-ssh:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2222:22"
    environment:
      - SSH_PASSWORD=${SSH_PASSWORD}
      - SSH_USER=${SSH_USER}
      - DUO_SKEY=${DUO_SKEY}
      - DUO_IKEY=${DUO_IKEY}
      - DUO_HOST=${DUO_HOST}
      - PRIVATE_KEY=${PRIVATE_KEY}
    volumes:
      - ./ansible/:/app/ansible
      - ./ansible/hosts:/etc/ansible/hosts:ro