name: SSH DUO Docker image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the ssh duo docker image tag
        run: |
          docker build . --tag ghcr.io/jdrozdnovak/ssh-duo-docker:$env:GITHUB_REF
          docker push ghcr.io/jdrozdnovak/ssh-duo-docker:$env:GITHUB_REF
      
      - name: Build and push the ssh duo docker image latest
        run: |
          docker build . --tag ghcr.io/jdrozdnovak/ssh-duo-docker:latest
          docker push ghcr.io/jdrozdnovak/ssh-duo-docker:latest