name: SSH DUO Docker image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  # Setting an environment variable with the value of a configuration variable
  env_var: ${{ vars.ENV_CONTEXT_VAR }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the ssh duo docker image
        run: |
          docker build . --tag ghcr.io/jdrozdnovak/ssh-duo-docker:$GITHUB_RUN_NUMBER --tag ghcr.io/jdrozdnovak/ssh-duo-docker:latest
          docker push ghcr.io/jdrozdnovak/ssh-duo-docker:$GITHUB_RUN_NUMBER
          docker push ghcr.io/jdrozdnovak/ssh-duo-docker:latest
        env:
          GITHUB_REF: ${{ vars.GITHUB_RUN_NUMBER }}
